/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package astrapharm;

/**
 *
 * @author SamHacker
 */
public class CustomerHome2 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String id;
    public CustomerHome2(String id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        med7 = new javax.swing.JLabel();
        med8 = new javax.swing.JLabel();
        med9 = new javax.swing.JLabel();
        med10 = new javax.swing.JLabel();
        med11 = new javax.swing.JLabel();
        med12 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        cart2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previous.setText("PREVIOUS");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        med7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med7MouseClicked(evt);
            }
        });
        getContentPane().add(med7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, 160));

        med8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med8MouseClicked(evt);
            }
        });
        getContentPane().add(med8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 160, 160));

        med9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med9MouseClicked(evt);
            }
        });
        getContentPane().add(med9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 160, 160));

        med10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med10MouseClicked(evt);
            }
        });
        getContentPane().add(med10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 160, 160));

        med11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med11MouseClicked(evt);
            }
        });
        getContentPane().add(med11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 160, 160));

        med12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med12MouseClicked(evt);
            }
        });
        getContentPane().add(med12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 160, 160));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 60, 60));

        cart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart2MouseClicked(evt);
            }
        });
        getContentPane().add(cart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/Customer Home 2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
        new CustomerHome1(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.out.println("Exit....");
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void med7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med7MouseClicked
        // TODO add your handling code here:
        new Xplendid(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med7MouseClicked

    private void med8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med8MouseClicked
        // TODO add your handling code here:
        new Rosunext(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med8MouseClicked

    private void med9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med9MouseClicked
        // TODO add your handling code here:
        new Lyzim(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med9MouseClicked

    private void med10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med10MouseClicked
        // TODO add your handling code here:
        new Cerelac(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med10MouseClicked

    private void med11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med11MouseClicked
        // TODO add your handling code here:
        new Ensure(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med11MouseClicked

    private void med12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med12MouseClicked
        // TODO add your handling code here:
        new Cac1000(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med12MouseClicked

    private void cart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart2MouseClicked
        // TODO add your handling code here:
        new Cart(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cart2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome2("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cart2;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel med10;
    private javax.swing.JLabel med11;
    private javax.swing.JLabel med12;
    private javax.swing.JLabel med7;
    private javax.swing.JLabel med8;
    private javax.swing.JLabel med9;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
