/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package astrapharm;

/**
 *
 * @author SamHacker
 */
public class CustomerHome1 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String id;
    public CustomerHome1(String id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        med1 = new javax.swing.JLabel();
        med2 = new javax.swing.JLabel();
        med3 = new javax.swing.JLabel();
        med4 = new javax.swing.JLabel();
        med5 = new javax.swing.JLabel();
        med6 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        cart1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        med1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med1MouseClicked(evt);
            }
        });
        getContentPane().add(med1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, 160));

        med2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med2MouseClicked(evt);
            }
        });
        getContentPane().add(med2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 160, 160));

        med3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med3MouseClicked(evt);
            }
        });
        getContentPane().add(med3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 160, 160));

        med4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med4MouseClicked(evt);
            }
        });
        getContentPane().add(med4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 160, 160));

        med5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med5MouseClicked(evt);
            }
        });
        getContentPane().add(med5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 160, 160));

        med6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med6MouseClicked(evt);
            }
        });
        getContentPane().add(med6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 160, 160));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 60, 60));

        cart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart1MouseClicked(evt);
            }
        });
        getContentPane().add(cart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 50, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/Customer Home.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CustomerHome2(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.out.println("Exit....");
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void med1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med1MouseClicked
        // TODO add your handling code here:
        new Panadol(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med1MouseClicked

    private void med2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med2MouseClicked
        // TODO add your handling code here:
        new BrufenDsSyp(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med2MouseClicked

    private void med3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med3MouseClicked
        // TODO add your handling code here:
        new Arinac(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med3MouseClicked

    private void med4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med4MouseClicked
        // TODO add your handling code here:
        new Calcee(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med4MouseClicked

    private void med5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med5MouseClicked
        // TODO add your handling code here:
        new Centrum(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med5MouseClicked

    private void med6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med6MouseClicked
        // TODO add your handling code here:
        new TootSiya(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_med6MouseClicked

    private void cart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart1MouseClicked
        // TODO add your handling code here:
        new Cart(this.id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cart1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome1("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cart1;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel med1;
    private javax.swing.JLabel med2;
    private javax.swing.JLabel med3;
    private javax.swing.JLabel med4;
    private javax.swing.JLabel med5;
    private javax.swing.JLabel med6;
    // End of variables declaration//GEN-END:variables
}
