/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package astrapharm;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SamHacker
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    String n;
    int nm=0;//no. of medicine in table
    int t=0;//total price var to print in textfield
    public EmployeeDashboard(String name) {
        initComponents();
        this.n=name;
        this.name.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        set = new javax.swing.JButton();
        ttext = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        ctext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        med = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        set.setBackground(new java.awt.Color(0, 153, 99));
        set.setText("PAID");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 70, 30));

        ttext.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        ttext.setText("Total");
        getContentPane().add(ttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 80, 30));

        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeKeyReleased(evt);
            }
        });
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 270, 30));

        ctext.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        ctext.setText("Code");
        getContentPane().add(ctext, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, 30));

        med.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(med);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 110, 30));

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 60, 50));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abdul Samad\\Downloads\\basit.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb=(DefaultTableModel)med.getModel();
         String q= tb.getValueAt(med.getSelectedRow(), 0).toString();
         String m=tb.getValueAt(med.getSelectedRow(), 1).toString();
         String a=tb.getValueAt(med.getSelectedRow(), 2).toString();
         System.out.println(q);
         System.out.println(m);
        JOptionPane.showMessageDialog(this, "Payment Received "+ a+" PKR","Payment Alert",1);
        
         tb.removeRow(med.getSelectedRow());
         
        new EmployeeDashboard(n).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.out.println("Exit....");
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyReleased
        // TODO add your handling code here:
        DB_Model_AP db= new DB_Model_AP();
        ResultSet rs;
         
        try{
            rs=db.CodeScan(Double.parseDouble(code.getText()));
            DefaultTableModel tb=(DefaultTableModel)med.getModel();
            
            
            if(rs.next()){
                nm++;
                code.setText("");
                System.out.println(rs.getString("name"));
                System.out.println(rs.getString("price"));
                
             String data[]={rs.getString("name"),Integer.toString(nm),rs.getString("price")};
               System.out.println(rs.getString("price"));
               int pt=(Integer.parseInt(rs.getString("price")));
             t=+pt;
           
             tb.addRow(data);
           
             total.setText(t+" PKR");
            }else{
            JOptionPane.showMessageDialog(this, "BarCode Not Matched", "BarCode", 2);
            }
               }
           catch(Exception e){
                   System.out.println(e);
                   }
    }//GEN-LAST:event_codeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JLabel ctext;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JTable med;
    private javax.swing.JLabel name;
    private javax.swing.JButton set;
    private javax.swing.JTextField total;
    private javax.swing.JLabel ttext;
    // End of variables declaration//GEN-END:variables
}
