/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package astrapharm;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author SamHacker
 */
public class EmployeeRegister extends javax.swing.JFrame {

    /**
     * Creates new form ShopkeeperRegister
     */
    public EmployeeRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        econtact = new javax.swing.JTextField();
        eemail = new javax.swing.JTextField();
        euser = new javax.swing.JTextField();
        epass = new javax.swing.JTextField();
        ecnic = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        erpass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 150, 20));

        l2.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 170, 20));

        l3.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 140, 20));

        l4.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 304, 130, 20));

        l5.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 354, 160, 20));

        l6.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 330, 20));

        ename.setText("Enter Employee Name");
        ename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enameMouseClicked(evt);
            }
        });
        ename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enameKeyReleased(evt);
            }
        });
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, -1));

        econtact.setText("Enter Contact #");
        econtact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                econtactMouseClicked(evt);
            }
        });
        econtact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                econtactKeyReleased(evt);
            }
        });
        getContentPane().add(econtact, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 100, -1));

        eemail.setText("Enter Email Address");
        eemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eemailMouseClicked(evt);
            }
        });
        eemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eemailKeyReleased(evt);
            }
        });
        getContentPane().add(eemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 140, -1));

        euser.setText("Enter User/ID");
        euser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                euserMouseClicked(evt);
            }
        });
        euser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euserKeyReleased(evt);
            }
        });
        getContentPane().add(euser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 325, 110, -1));

        epass.setText("Set Password");
        epass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epassMouseClicked(evt);
            }
        });
        epass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                epassKeyReleased(evt);
            }
        });
        getContentPane().add(epass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 375, 110, -1));

        ecnic.setText("Enter CNIC#");
        ecnic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ecnicMouseClicked(evt);
            }
        });
        ecnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ecnicKeyReleased(evt);
            }
        });
        getContentPane().add(ecnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, -1));

        code.setText("Enter Admin Authorized Code");
        code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeMouseClicked(evt);
            }
        });
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 325, 190, -1));

        erpass.setText("Re-type Password");
        erpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                erpassMouseClicked(evt);
            }
        });
        getContentPane().add(erpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 375, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 110, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 140, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrapharm/3. Employee.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DB_Model_AP db= new DB_Model_AP();
        int st=0;
        if(epass.getText().equals(erpass.getText())){
        st=db.EmployeeRegister(ename.getText(), econtact.getText(), eemail.getText(),ecnic.getText(),euser.getText(),epass.getText());
         if(st!=0){
        JOptionPane.showMessageDialog(this, "You are Redirected to Login Page.","Acount Created",1);
        new EmployeeLogin().setVisible(true);
        this.dispose();
         }else{JOptionPane.showMessageDialog(this, "Some Error Occur","Alert",1);}
        }else{
        JOptionPane.showMessageDialog(this, "Enter Both Password Same","Passowrd Mismatch",2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new EmployeeLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void enameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enameMouseClicked
        // TODO add your handling code here:
        ename.setText("");
    }//GEN-LAST:event_enameMouseClicked

    private void econtactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_econtactMouseClicked
        // TODO add your handling code here:
        econtact.setText("");
    }//GEN-LAST:event_econtactMouseClicked

    private void eemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eemailMouseClicked
        // TODO add your handling code here:
        eemail.setText("");
    }//GEN-LAST:event_eemailMouseClicked

    private void ecnicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ecnicMouseClicked
        // TODO add your handling code here:
        ecnic.setText("");
    }//GEN-LAST:event_ecnicMouseClicked

    private void euserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euserMouseClicked
        // TODO add your handling code here:
        euser.setText("");
    }//GEN-LAST:event_euserMouseClicked

    private void codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeMouseClicked
        // TODO add your handling code here:
        code.setText("");
    }//GEN-LAST:event_codeMouseClicked

    private void epassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epassMouseClicked
        // TODO add your handling code here:
        epass.setText("");
    }//GEN-LAST:event_epassMouseClicked

    private void erpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_erpassMouseClicked
        // TODO add your handling code here:
        erpass.setText("");
    }//GEN-LAST:event_erpassMouseClicked

    private void enameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enameKeyReleased
        // TODO add your handling code here:
        Pattern p1=Pattern.compile("[a-zA-Z ]{3,15}");
        Matcher m1=p1.matcher(ename.getText());
        if(!m1.matches()){
        l1.setText("Use atleast 3 characters");
        }else{
        l1.setText("");
        }
    }//GEN-LAST:event_enameKeyReleased

    private void econtactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_econtactKeyReleased
        // TODO add your handling code here:
        Pattern p2=Pattern.compile("(030|031|032|033|034)+[0-9]{8}");
        Matcher m2=p2.matcher(econtact.getText());
        if(!m2.matches()){
        l2.setText("e.g 03(complete 11 digits)");
        }else{
        l2.setText("");
        }
    }//GEN-LAST:event_econtactKeyReleased

    private void eemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eemailKeyReleased
        // TODO add your handling code here:
        Pattern p3=Pattern.compile("[a-zA-Z0-9]{3,}+(@)+(gmail|hotmail|yahoo)+(.com)");
        Matcher m3=p3.matcher(eemail.getText());
        if(!m3.matches()){
        l3.setText("e.g abc12@xyz.com");
        }else{
        l3.setText("");
        }
    }//GEN-LAST:event_eemailKeyReleased

    private void ecnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ecnicKeyReleased
        // TODO add your handling code here:
        Pattern p4=Pattern.compile("^\\d{5}-\\d{7}-\\d$");
        Matcher m4=p4.matcher(ecnic.getText());
        if(!m4.matches()){
        l4.setText("e.g 42000-0000000-0");
        }else{
        l4.setText("");
        }
    }//GEN-LAST:event_ecnicKeyReleased

    private void euserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euserKeyReleased
        // TODO add your handling code here:
        Pattern p5=Pattern.compile("[a-zA-Z0-9]{3,}+(@emp)");
        Matcher m5=p5.matcher(euser.getText());
        if(!m5.matches()){
        l5.setText("ID should be xy12@emp");
        }else{
        l5.setText("");
        }
    }//GEN-LAST:event_euserKeyReleased

    private void epassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epassKeyReleased
        // TODO add your handling code here:
        Pattern p6=Pattern.compile("[a-zA-z0-9!@#$%^&*]{8,}");
        Matcher m6=p6.matcher(epass.getText());
        if(!m6.matches()){
        l6.setText("It should have atleast 8 characters(+special) ");
        }else{
        l6.setText("");
        }
    }//GEN-LAST:event_epassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField ecnic;
    private javax.swing.JTextField econtact;
    private javax.swing.JTextField eemail;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField epass;
    private javax.swing.JTextField erpass;
    private javax.swing.JTextField euser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    // End of variables declaration//GEN-END:variables
}
